version: '3'
services:
  prometheus:
    container_name: prm
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090

  debian:
    build: ./debian
    container_name: deb
    tty: true
    ports:
      - 9100:9100
    depends_on:
      - prometheus
